name: Build Frontend

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend
        env:
          GIT_TAG: ${{ github.ref_name }}
          VITE_PINBO_CONTRACT_ADDRESS: "0xd142B29992Da1CEfB429e303500A90Bbe3e01118"
          VITE_CONTRACT_DEPLOY_BLOCK: "24664869"
          VITE_CHAIN_ID: "1"
          VITE_RPC_URL: "https://ethereum-rpc.publicnode.com"
          VITE_ENS_RPC: "https://1.rpc.thirdweb.com"

      - name: Archive build
        run: tar -czf pinbo-${{ github.event.inputs.tag || github.ref_name }}.tar.gz -C frontend/build .

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: pinbo-${{ github.ref_name }}.tar.gz
